### ISSUE TITLE
How to skip theming context menus and preferences window

### ISSUE THREAD

**Issue by intika** [FranklinDM/MaterialMoon#6]
Following [palemoon forum](https://forum.palemoon.org/viewtopic.php?f=45&t=14631&p=152369&sid=82f8450d0dd768a8727770efd349a2b7#p152369) 

I guess it's more reliable over here... A Material Dark version would be really cool... 

It's not linux dependent... i would like to keep the theme native for
1. Menus drop box (context menus)
2. Preferences window

i think it's something under "chrome/global/" if you have any idea where i can look to edit code let me know i will check that in details myself, test etc... if you have the time of course otherwise let me know when you can :)

thanks

**Comment by fofajardo** [comment]
**Preferences window:**
for the content pane - global/preferences.css, prefPane selector, change background-color
for the main background - global/global.css, line 31, adapts to system background (if im not mistaken)

**App menu popup:**
It's controlled by os-specific styling 
You can change the background/text color through these selectors:
#appmenuPrimaryPane
#appmenuSecondaryPane

**Comment by intika** [comment]
Thanks a lot :)
